image:
  file: .gitpod.Dockerfile

tasks:
  - init: echo 'Builing Fission Go Code'
    command: go mod download

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: false
    addLabel: false